var myNumber;
myNumber = 5;
var myOtherNumber;
myOtherNumber = 5;
var myTotal;
myTotal = myNumber * myOtherNumber;
var myName;
myName = "Paulina Habbecke";
var myCombo;
myCombo = "myNumber + myOtherNumber";
var myOtherCombo;
myOtherCombo = myNumber + myOtherNumber;
var myRemainder;
var myRemainder = myNumber/5;
var i = 2;
var int = 4;
var myBoolean = false;